Meny customer admin
Darkdusk234/RebelAllianceBank pull request #9
Opened 2024-11-22 12:57 UTC by tantting

## Description

Provide a clear description of what the PR does and why its relevant

## Related Issue ( optional )

Link to any related issue

## Changes

Describe the changes in more detail, if necessary include explanation of why some choices were made.

## Screenshots & GIFs ( optional )

media to provide more visual context if necessary

## Notes & Comments

General notes and comments, such as if there is things to consider ahead of deployment

2024-11-22 13:27 UTC, JosefForkman requested changes
Move all menu logic to a own class. Otherwise a good code

2024-11-22 13:27 UTC, JosefForkman commented on RebelAllianceBank/Classes/Bank.cs
> +using System.Xml.Schema;
Remove unused code

2024-11-22 14:15 UTC, tantting commented
REquested changes have been done and pushed.

2024-11-23 08:25 UTC, JosefForkman approved these changes
Much better when the code is in its own class

2024-11-25 13:13 UTC, JosefForkman approved these changes

2024-11-25 13:14 UTC, JosefForkman approved these changes

2024-11-25 13:15 UTC, Darkdusk234 approved these changes
Well Done

2024-11-25 13:15 UTC, merged